### ISSUE TITLE
Graph not showing correctly

### ISSUE THREAD

**Issue by Rikkie80** [aex351/home-assistant-neerslag-app#18]
Installed the neerslag-card via HACS and integration. Sensors are there, and card is showing up in Lovelace, but I don't think the style is as it should be... What is wrong? The 2 sensors are active and provide data (which is now that it will not rain the coming hours). 
![image](https://user-images.githubusercontent.com/42078225/132469346-ab7b9f0b-48ff-4ebd-9baf-515a6317a3c5.png)
![image](https://user-images.githubusercontent.com/42078225/132469770-c969e15a-c898-4b63-a592-fc7f1154a4a1.png)

**Comment by aex351** [comment]
It seems the Neerslag App has not been loaded correctly and/or you are not running the latest version.  Because the 'legends' Buienalarm and Buienradar should not be displayed. Try reinstalling the Neerslag App (recommended). If you use the Neerslag App, make sure to delete/remove the Neerslag Card. Both can't be run at the same time.

**Comment by benv666** [comment]
I find this fascinating, because I see exactly the same thing happening. Used to have the old neerslag-card, which I removed all traces of on my filesystem (e.g. a `find . -iname '*neerslag*'` finds `./custom_components/neerslag/home-assistant-neerslag-card/neerslag-card.js` and it's .gz variant.).

Once every blue moon I see the style as I think it's supposed to be, but then I reload/ctrl-f5/refresh/stand on my head and it turns back to grey.
The graph does seem to indicate the correct thing though, when there's anything to display.
![image](https://user-images.githubusercontent.com/165034/134557132-b48d797b-4c83-41b6-aa2d-001e1cabc6f9.png)

So I'm willing to believe this is due to the old stuff still being somewhere present, but please enlighten us as to how to get rid of it.

**Comment by aex351** [comment]
It seems to be a caching issue. Not an issue with the integration itself. Can you tell me what version of the Neerslag App you are running? Also try clearing your cache and restart Home Assistant. That should resolve the issue.

**Comment by benv666** [comment]
Can you tell me where that cache should be located on my server? I have a brand new tablet that's also showing this issue.
Home Assistant has been restarted several times today (and this week as well, have been running with this neerslag-app for more than a week)

**Comment by aex351** [comment]
The cache is located on your 'client' devices. Not the 'server'. Try clearing your browser cache and/or mobile app cache and restart Home Assistant. You can verify this by opening up a browser window in private/incognito mode to check that everything currently is working as expected.

Also make sure to not have the 'Neerslag Card' installed next to the 'Neerslag App'.

**Comment by benv666** [comment]
Well, that means that browser cache is not the problem then.
Again, I have a brand new tablet that literally was installed yesterday for the sole purpose of displaying a Home Assistant panel on my wall. Great coincidence, but that does factor out the cache.
To doublecheck I also tried incognito mode in Brave, same story:
![image](https://user-images.githubusercontent.com/165034/134628463-0ef65715-f96b-48a6-bb64-ea7f3be45a88.png)

I don't have any other neerslag related frontend thing loaded ... as far as I am aware.
Ran a `grep -Ri neerslag` on the home assistant configuration folder, all hits are either in the HA `.storage` folder, `homeassistant.log`, or the `custom_components/neerslag/` folder - nothing that looks even remotely significant.

How can we properly troubleshoot this?

**Comment by Rikkie80** [comment]
I performed the same actions:

- deinstalling 'Neerslag-card'
- clearing Cache
- Reinstall 'Neerslag app'

But no positive result. Still seeing the grey graph on all devices (incl. devices that never opened my HA before)

**Comment by aex351** [comment]
I can't reproduce the issue you are describing. The Neerslag App/Card is a web component so it runs as-is. It could be that another component is causing these issues for you and is overriding the graph configuration. Because what you are seeing is simply not possible with the default Neerslag App/Card configuration.

Make sure to not install the Neerslag Card if you use the Neerslag App and vice versa.

Instead of using the Brave browser. Try Chrome to see if that works. You can also check the browser developer console (press F12) to see what's being loaded and if there are errors. Please let me know if there are any.

**Comment by benv666** [comment]
Brave vs Chrome is not the issue here -- again, also seeing this issue on the brand new tablet with whatever browser that is (Chrome I suppose) .
I also believe this is caused by either some old ghost of neerslag-card that's hiding where I haven't looked, OR some other component, but what I don't know is how to find that out without uninstall everything. 
HA is too integrated in my household to simply wipe and start from scratch, so that's not an option for this.

That said, I'll find some time to go through the process of disabling all other frontend integrations and if that helps re-enabling them one by one.
Thanks for the support so far at least! :)

**Comment by Rikkie80** [comment]
I finally found my issue! I had an old card installed in the custom-components folder: 'lovelace-buien-rain-card'. After removal the graph is displayed as expected.

**Comment by benv666** [comment]
Give this man a cookie - exact same thing at my installation. Thanks @Rikkie80 !

Would it be possible to flag the `lovelace-buien-rain-card` as incompatible?

**Comment by aex351** [comment]
Thanks for the debug work @Rikkie80. It then seems that the 'lovelace-buien-rain-card' is overriding the configuration of the Neerslag App/Card. That would explain why you are seeing the graph the way you are doing. 

While this still isn't an issue with the Neerslag App/Card itself, as it is caused by third party components, I will have a look to see how I can isolate the Neerslag App/Card from other components. That should prevent similar issues from occurring in the future.

@benv666, such logic should be provided by Home Assistant or HACS. I think if the Neerslag App/Card get further isolated there won't be a need for it.

**Comment by Ronker32** [comment]
Got the same issue, came here and fixed it. I found the 'lovelace-buien-rain-card' through _Edit dashboard_ and then went to _Manage resources_ which is where I found the card. After deleting it and accepting the prompt to refresh the page, the card showed correctly again. Thanks!

**Comment by BebeMischa** [comment]
I also face this issue.
HA supervised core-2021.9.7
Neerslag app ver. 8359e71
Firefox browser latest

Did all the recomended steps:

Reinstall of the app
Clearing cache of the browser
Removing the card directly in the folders using SMB
Reinstall again
Restart HA

Nothing helps, nothing useful in the logs...

But stil looking at this:

![image](https://user-images.githubusercontent.com/73079275/135727539-bd227bec-a2b5-42b0-9066-f910fdcc7bcd.png)


I'm out of ideas.

**Comment by BebeMischa** [comment]
Never mind, got it working, don't know why, but a reboot of the HA server was needed.

**Comment by EDelsman** [comment]
I have the same thing. It was working fine until recently. Clearing the cache does not work. Also reloading from HACS and rebooting does not. What is remarkable though: in Chrome on a CTRL-F5, I shortly see the right graph, and then the other grid pattern is drawn over it as shown by the OP.  When I hover the mouse over a point of the graph line, everything disappears until I move the mouse away again.

Makes me wonder, could some other integration do a card-mod by mistake? Is there some way I can check that?

**Comment by defisit** [comment]
> I have the same thing. It was working fine until recently. Clearing the cache does not work. Also reloading from HACS and rebooting does not. What is remarkable though: in Chrome on a CTRL-F5, I shortly see the right graph, and then the other grid pattern is drawn over it as shown by the OP. When I hover the mouse over a point of the graph line, everything disappears until I move the mouse away again.
> 
> Makes me wonder, could some other integration do a card-mod by mistake? Is there some way I can check that?
> 
> Did install Plotly, history-explorer-card and ui_lovelace_minimalist lately. Any-one else also sees a correlation with any of those?

Yes, today I installed history-explorer-card and after that neerslag-app started behaving like explained here.

**Comment by EDelsman** [comment]
Removed history explorer, refresed and tada! All is well again. That is sad, I would like to keep both...

**Comment by aex351** [comment]
The `history-explorer-card` is overwriting the `neerslag-card` chart configuration. That is why you can observe that the `neerslag-card` is loading correctly at first and quickly being redrawn with the 'new' configuration as set by the `history-explorer-card`. The `history-explorer-card` should not overwrite the configuration of the `neerslag-card`.

This appears to be the same issue as with the `lovelace-buien-rain-card`. I did not found a way to prevent other third party components from changing the configuration of the `neerslag-card`. Up until now only two third party components appear to do this:
- `lovelace-buien-rain-card`
- `history-explorer-card` 

I will add the `history-explorer-card`  to the list of incompatible components until this issue gets resolved. This means the `neerslag-card` will show an error message. The author of the `history-explorer-card` should ensure that the component doesn't modify the configuration of other charts.

**Comment by EDelsman** [comment]
I posted a bug in the history card. I suspected the configuration already since the history card is about the only card I know that requires a unique name in order to make sure it does not mix up the settings with other cards. I will relay the information in the bug I posted there.

**Comment by alexarch21** [comment]
Developer of the history explorer card here.

> The history-explorer-card is overwriting the neerslag-card chart configuration. 

I'd be very much interested what technical steps and details made you come to this conclusion. The 'overwriting' may be simply related to loading order. Maybe your card just overwrites other cards configuration in a similar manner if the loading order was reversed. So some more technical details will certainly be helpful here.

> The author of the history-explorer-card should ensure that the component doesn't modify the configuration of other charts.

It doesn't. 

>  I suspected the configuration already since the history card is about the only card I know that requires a unique name in order to make sure it does not mix up the settings with other cards

With other instances of the _history explorer card_ only. The card will never access or modify the settings of any other custom cards.

**Comment by aex351** [comment]
The order in which custom cards get loaded should not affect the configuration of the `neerslag-card`. It has been observed that in either case, the `neerslag-card` loads correctly and the configuration gets changed after the `history-explorer-card` has been fully loaded. The stated report also mentions that the `history-explorer-card` doesn't even need to be actively visible on the dashboard for this to happen. 

- There are no reports that the `neerslag-card` modifies other cards;
- The reports are that up until now there are two cards that modify the `neerslag-card`. One of them `lovelace-buien-rain-card` is a very old card. And the second one is the `history-explorer-card`. Both use ChartJS. 

While it may not be the intent of the `history-explorer-card` to modify the configuration of another card. In this case the `neerslag-card`. We can observe that it does.

**Comment by alexarch21** [comment]
Without further technical details I cannot help with this.

**Comment by aex351** [comment]
What further technical details do you require?

You should install the `neerslag-card` (or better the `neerslag-app`) and determine yourself why the  `history-explorer-card` is causing it to change the configuration of another card. For now I will add the `history-explorer-card` to the list of incompatible components until this issue gets resolved.

**Comment by alexarch21** [comment]
It is just as likely that the problem is with the neerslag card not correctly isolating its global data as it is with the history explorer card 'overwriting' something. I'm open to fix anything on my side if there's really an issue, but until now no other reports of that nature came in from any other cards, nor are the native HA cards affected (who also use Chartjs). I'm also open working together to fix this issue, but I will not spend my free time debugging your card. That's your job.

Without more technical evidence, I'm afraid I will have to close this issue on my side then.

**Comment by aex351** [comment]
The `history-explorer-card` is modifying the configuration of the `neerslag-card`. It is not the `neerslag-card` modifying the configuration of the `history-explorer-card`. There is sufficient reasoning for you as author of the `history-explorer-card` to research why 'your' own card is actively modifying another card. 

I already explained that I researched/debugged the `neerslag-card` before when this same issue happened with the old and outdated `lovelace-buien-rain-card` and could find no problems with the `neerslag-card` itself. However, I can not prevent a third party card from modifying the `neerslag-card`. 

I suggest you install the `neerslag-card` together with the `history-explorer-card` and determine how the `history-explorer-card` is modifying the configuration. If there are reports that the `neerslag-card` is modifying the configuration of `history-explorer-card` I will do the same. If you need any help, just let me know.

**Comment by alexarch21** [comment]
The fact that the exact same symptoms appeared with a completely unrelated card, the buien rain card, old or not doesn't matter, is a pretty tell tale sign that the issue here is with your card. One can be a coincidence. Twice the same symptom from two completely unrelated sources - that is a pattern. I suggest you research on how to better isolate your card from others to avoid these kind of effects in the future with more cards.

In the absence of any more technical evidence, I have closed this issue on my side as invalid.

**Comment by aex351** [comment]
This issue is not caused by the `neerslag-card`. I already explained I researched this before. I did many trial and errors. So there is no more 'technical evidence' to give. I am not going to continue this by debugging and fixing the code of `history-explorer-card`. You choose to ignore the fact that the `history-explorer-card` is modifying code from another card, that is up to you. To me I will classify `history-explorer-card` as malicious and encourage my users to stay away from it.

**Comment by groenmarsmannetje** [comment]
Maybe I just remove both components...

**Comment by aex351** [comment]
- I already explained I did the needed research to conclude the problem is not with the `neerslag-card`;
- It is not the `neerslag-card` that modifies code/configuration. It is the `history-explorer-card` that modifies code/configuration.

As this all is open-source and free of charge to use. Feel free to contribute.

**Comment by groenmarsmannetje** [comment]
This is the most stupid solution I have ever seen been created by a developer. But it is a nice example that can be used in any lesson about "how developers can loose themself in creating workarounds for technical issues and forgot about User Experience".

![image](https://user-images.githubusercontent.com/46958454/152568904-e285545a-fe50-440d-a7d6-1888b74dba70.png)

**Comment by alexarch21** [comment]
For some reason I was still subscribed to this. This is completely absurd. I'm really sorry for the bad experience for users like [groenmarsmannetje](https://github.com/groenmarsmannetje), but this 'solution' is so ridiculous that it almost made me laugh.

To reiterate this, and yes I know I'm basically talking to a wall here - it is **_technically impossible_** for the history explorer card to "overwrite" this card. My card uses a full anonymous closure that encapsulates the entire card and all dependencies (including chartjs). To explain this for non-developers, this is a feature provided by the Javascript standard to _specifically_ keep code from interfering with other code on the same website. It's considered standard and best practice for web development and it makes it _impossible_ to do what this developer here claims my card would do. If it would be possible, then that would be one of the most serious vulnerabilites in the history of Javascript and billions of website would be affected - and we're clearly not seeing that....

I really don't know what else I can say.

Oh yeah, just maybe that the neerslag card doesn't do any of this kind of encapsulation, doesn't isolate itself at all and doesn't follow any of these established good practices. I checked the source. I mean I'm not here to judge. But maybe, just _maybe_ the reason might be somewhere around there....

Anyway, unsubscribing now.

**Comment by aex351** [comment]
- `neerslag-card` itself does not have a global `r` variable. 
- The only `r` variable used in the code is that of the ChartJS annotation plugin; 
- If the `history-explorer-card` would be truly 'isolated' - which it claims it is - then it should not affect the `neerslag-card` by overwriting the configuration.

**Comment by groenmarsmannetje** [comment]
@alexarch21  thank you for explaining. I understand your concerns. I also viewed the code of @aex351 and  although I am not a JavaScript developer, I also have doubts and see the possible pitfalls that you are trying to make @aex351 aware of.

**Comment by aex351** [comment]
Anyone is welcome to review the code and provide contributions for improving it. 

For now my conclusion remains that the issue described is not with the `neerslag-card`. There are many other cards that use ChartJS that don't cause the `neerslag-card` to break. If I would be the author of the `history-explorer-card` I would want to research why this happens. As I researched and tested this from the `neerslag-card` perspective. However, the only reply I am reading is that I need to provide more 'technical evidence' as to why the `history-explorer-card` is breaking the `neerslag-card`. I have no more 'technical evidence' to give. And let it be clear that I installed the `history-explorer-card` to research what could be the root cause for the `neerslag-card` to break down. I could not find any. 

Based on the response of the author of the `history-explorer-card` and the unwillingness to actually explore the possible root cause to be with the `history-explorer-card`, I marked the card as incompatible with the `neerslag-card` until the issue gets resolved. This to inform the users of the `neerslag-card` that the `history-explorer-card` will produce an error. Which prevents them from creating additional issues in this Github.

**Comment by alexarch21** [comment]
@[groenmarsmannetje](https://github.com/groenmarsmannetje)
You can probably make his code work by putting it into its own local scope. They main issue is that he just basically copy and pasted everything together, including his dependencies. That's not how you create a workable distribution build.

You can try to put his entire code into a closure by doing this:
```
(function(){
... add his entire code here, including his copy and pasted dependencies ...
})();

```
Pretty sure this will make things work and keep other 'evil' cards from 'overwriting' his own ;)

**Comment by groenmarsmannetje** [comment]
@alexarch21 thanks, I will try this tomorrow. Just to rule this out. Seems as a very easy thing to do, even for a rusty Java developer like me. My compliments for your code by the way. Very nicely structured and well to read for an outsider like me.

**Comment by BebeMischa** [comment]
I'm just a viewer here, As I use the neerslag thing. I do not use the history thing, so I'm not affected by this issue. But I'm interested in what's going on with stuff I use. And so I follow this discussion too as a subscriber on this channel.

So what I see is, that @aex351 is continuously repeating, that the issue is tested, but I nowhere see any test results. I do not see malicious pieces of code flying around to prove the influence of an another card. Only words, no any evidence.

I'm not a coder, but I'm a crisis manager in a hospital, so I do know a bit about, how things have to go, when two party's are having different view.

So now I kindly ask ask you, @aex351 , to deliver some fact's, that empowers your words, so this discussion can get somewhere.

If you refuse that, as a user of your software I will feel in need to remove your code from my machine and also spread the word around, that your work can't be trusted.

Please, get down to the ground and try to collaborate, step out of the bubble of being superior. You are not, I'm not, nobody is.
Try to solve this issue, not pointing at others to do it, become a leader taking this case to a good end.

Thanks for reading this.

**Comment by aex351** [comment]
Encapsulating the entire code as suggested by @alexarch21 does not resolve the described issue. See below for results:

Home Assistant loads these custom cards in random order. There are two scenario's that can happen:
- `neerslag-card` gets loaded then the `history-explorer-card` = problem
- `history-explorer-card` gets loaded then the `neerslag-card` = all works fine

When there is a problem. The `neerslag-card` configuration has been overwritten and the graph is broken. As seen in earlier screenshots. Trying to interact with the graph results in the following stack trace:

![image](https://user-images.githubusercontent.com/79757148/152621992-800542b9-5a1a-4e1a-832e-6e7843e060f2.png)

Following this stack-trace we end up in the `history-explorer-card`:

![image](https://user-images.githubusercontent.com/79757148/152622025-012d9df1-57dc-40b6-937b-93ed7e759282.png)

**Comment by alexarch21** [comment]
That's a crash in chartjs.

Things like this can happen due to incompatibilities of chartjs versions and the way chartjs' plugin system works. A notification from one chartjs instance can be routed to the other, sometimes due to the browser mixing up the code in the cache. That should normally be caught by proper encapsulation though. If it isn't, then this is something that has be fixed in chartjs itself, there's nothing the calling code can do.

I'll take a closer look at that too tomorrow.

**Comment by groenmarsmannetje** [comment]
@aex351 I think I got it solved, but I am not an expert on this so you need to verify yourself too.

Locally I moved the beforeDraw plugin to the level of the chart (options -> plugins) that you initialize. Current it is inititialized on global plugins level in your chart. And after that the neerslag card works again.

And maybe @alexarch21 can also confirm if this might be the solution. Actually his hint that there was something globally defined helped me to look for this. So thanks again @alexarch21.

If you have verifies that this fix indeed and works, please release it.

**Comment by aex351** [comment]
Home Assistant uses ChartJS for its charts. It is a key component for all of the default charts.
- https://github.com/home-assistant/frontend/blob/9be5a15c77d752ac6626becdb72acee6a659031d/package.json#L99

The current situation remains:

- The `neerslag-card` works with Home Assistant that uses ChartJS (both version 3.x);
- The `neerslag-card` does not break other cards (no reports exist); 
- The `neerslag-card` gets broken when 'certain' other cards (i.e. `history-explorer-card`) are used that have implemented ChartJS. 

What has been observed however is that both the `neerslag-card` and `Home Assistant` use ChartJS version 3.x. Which is an up-to-date version. 'Pie Chart' (actual name: `power-usage-card`) uses an old ChartJS version (version 2.7.x that dates from 28 okt. 2017). It could well be that the `history-explorer-card` uses an old version of ChartJS or configuration that causes issues. I can't determine this. 

This is something @alexarch21 will need to look in to.

**Comment by alexarch21** [comment]
You're deleting the comments from people like @groenmarsmannetje who described a possible fix for your card that solved the issue. This is just pathetic. I'm done with this. If someone wants to fork this card and still encounters problems with my card once the proposed fixed to the neerslag card were applied, I'd be happy to help. But certainly not with the original repo owner.

>  And also in that case the style of the neerslag card is affected and you cannot interact with it.

Next candidate for his malicious cards red box...

**Comment by BebeMischa** [comment]
My comment is deleted too... OK, i know enough. This is the end of Neerslag card on my machine. Deleting now... Bye bye...

**Comment by aex351** [comment]
@alexarch21, he did not propose a fix. He tried using 'your' proposed fix / which I also tested. Which didn't work. He even deleted one of his own comments in which he stated he got it working. However, it is clear that you are not doing any testing to get the `history-explorer-card` fixed. 

Furthermore I reserve the right to moderate this thread. Stay on-topic. Any comments that are not on-topic or are abusive I will delete or edit.

**Comment by groenmarsmannetje** [comment]
Indeed I removed my comment myself because at a closer look, although the line on the chart was drawn correctly the styling was still wrong and also the beforeDraw event wasn’t actually triggered after I moved it. It is clear that I do not have enough knowledge to dive deeper in this.

**Comment by aex351** [comment]
It seems that starting with version 1.0.16 of the `history-explorer-card` the incompatibility issues have been resolved by the author @alexarch21 . For this reason I have removed the plugin from the list of incompatible plugins starting with version 2022.02.10.0 of the `neerslag-card`. 

However, as there is no clear indication by the author that he actively fixed the issue. It might be accidental that he updated his plugin in such a way that the `history-explorer-card` doesn't impact other cards.

For the `neerslag-card` I am trying to keep the code as simply as possible. No auto-generating code w/ build process. And it could well be possible that in the future again another developer / third party plugin comes along that also finds a way to cause incompatibility issues. For this reason I will explore a way to migrate away from ChartJS and use another chart solution.
